version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Python packages...
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo Building the Lambda deployment package...
      - zip -r lambda_function.zip lambda_function.py .

  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - lambda_function.zip
  discard-paths: yes
  base-directory: .
